import React from "react";

export const metadata = {
  title: "Acerca de nosotros",
  description: "Generated by Next.js",
};

const about = () => {
  return <div>about</div>;
};

export default about;
